# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 045c48a23fe7756aa08b2019a0ed568891468865456ac5427b9287d31793a186358d7094e20ede9db86b3d74e94b3b69c9a63a4e530b00ed5bd179ba2a8addbb

test:
  secret_key_base: f02670b815befb7200b421d95e22cb024a3d568f63cdf30a122d59f092d25f2a9a009778d4d9ada713c04a99e1dc3c41ab51d41dbb5a338b096d46f139439e85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
